export interface Event {
	id: string;
	title: string;
	description: string;
	dates: EventDate[];
	location: string;
	venue: string;
	region: "mexico-city" | "monterrey" | "guadalajara" | "cancun";
	image: string;
	category:
		| "concert"
		| "sports"
		| "theater"
		| "festival"
		| "comedy"
		| "conference"
		| "exhibition";
	artist?: string;
	organizer: string;
	ticketTypes: TicketType[];
}

export interface EventDate {
	date: string;
	times: string[];
}

export interface TicketType {
	id: string;
	name: string;
	price: number;
	available: number;
	description: string;
}

export interface User {
	id: string;
	email: string;
	firstName: string;
	lastName: string;
	phone?: string;
}

export interface Order {
	id: string;
	userId?: string;
	email: string;
	eventId: string;
	tickets: {
		ticketTypeId: string;
		quantity: number;
		price: number;
	}[];
	total: number;
	createdAt: string;
}

export const mockEvents: Event[] = [
	// Music & Concerts
	{
		id: "1",
		title: "Summer Music Festival 2025",
		description:
			"Join us for the biggest music festival of the summer featuring top artists from around the world.",
		dates: [
			{ date: "2025-07-15", times: ["18:00"] },
			{ date: "2025-07-16", times: ["18:00"] },
			{ date: "2025-07-17", times: ["18:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/summer-music-festival-crowd-stage.jpg",
		category: "festival",
		artist: "Various Artists",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "1-1",
				name: "General Admission",
				price: 899,
				available: 5000,
				description: "Standing room access",
			},
			{
				id: "1-2",
				name: "VIP",
				price: 2499,
				available: 500,
				description: "VIP lounge, premium viewing area",
			},
			{
				id: "1-3",
				name: "Premium",
				price: 4999,
				available: 100,
				description: "Meet & greet, backstage access",
			},
		],
	},
	{
		id: "2",
		title: "Bad Bunny World Tour",
		description:
			"The Puerto Rican superstar brings his electrifying performance to Mexico City.",
		dates: [{ date: "2025-06-20", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Estadio Azteca",
		region: "mexico-city",
		image: "/reggaeton-concert-lights-crowd.jpg",
		category: "concert",
		artist: "Bad Bunny",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "2-1",
				name: "General",
				price: 1299,
				available: 30000,
				description: "Stadium seating",
			},
			{
				id: "2-2",
				name: "Floor",
				price: 3999,
				available: 5000,
				description: "Standing floor access",
			},
			{
				id: "2-3",
				name: "VIP",
				price: 8999,
				available: 500,
				description: "Premium seating with amenities",
			},
		],
	},
	{
		id: "3",
		title: "Rock en Español Fest",
		description:
			"Celebrating the best of Latin rock with legendary and emerging artists.",
		dates: [{ date: "2025-08-05", times: ["16:00"] }],
		location: "Monterrey, Mexico",
		venue: "Parque Fundidora",
		region: "monterrey",
		image: "/rock-concert-outdoor-festival.jpg",
		category: "festival",
		artist: "Caifanes, Café Tacvba, Zoé",
		organizer: "Apodaca Group",
		ticketTypes: [
			{
				id: "3-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "Festival grounds access",
			},
			{
				id: "3-2",
				name: "VIP",
				price: 1999,
				available: 1000,
				description: "VIP area with bar",
			},
		],
	},
	{
		id: "4",
		title: "Jazz Under the Stars",
		description:
			"An intimate evening of smooth jazz in a beautiful outdoor setting.",
		dates: [
			{ date: "2025-05-10", times: ["19:00"] },
			{ date: "2025-05-11", times: ["19:00"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Jardín Botánico",
		region: "guadalajara",
		image: "/jazz-band-saxophone-outdoor-evening.jpg",
		category: "concert",
		artist: "Patricia Zárate Quartet",
		organizer: "Jazz México Foundation",
		ticketTypes: [
			{
				id: "4-1",
				name: "Regular",
				price: 599,
				available: 500,
				description: "Garden seating",
			},
			{
				id: "4-2",
				name: "Premium",
				price: 1099,
				available: 100,
				description: "Front row with table service",
			},
		],
	},
	{
		id: "5",
		title: "Electronic Dreams Festival",
		description:
			"Three days of electronic music featuring world-class DJs and producers.",
		dates: [
			{ date: "2025-08-10", times: ["16:00"] },
			{ date: "2025-08-11", times: ["16:00"] },
			{ date: "2025-08-12", times: ["16:00"] },
		],
		location: "Cancún, Mexico",
		venue: "Beach Arena",
		region: "cancun",
		image: "/electronic-music-dj-lights-festival-crowd.jpg",
		category: "festival",
		artist: "Tiësto, Martin Garrix, David Guetta",
		organizer: "EDM Mexico",
		ticketTypes: [
			{
				id: "5-1",
				name: "1-Day Pass",
				price: 1299,
				available: 3000,
				description: "Single day access",
			},
			{
				id: "5-2",
				name: "3-Day Pass",
				price: 2999,
				available: 2000,
				description: "Full festival access",
			},
			{
				id: "5-3",
				name: "VIP 3-Day",
				price: 5999,
				available: 300,
				description: "VIP amenities all days",
			},
		],
	},
	{
		id: "6",
		title: "Coldplay - Music of the Spheres",
		description:
			"Experience the spectacular world tour with stunning visuals and unforgettable music.",
		dates: [
			{ date: "2025-03-25", times: ["20:30"] },
			{ date: "2025-03-26", times: ["20:30"] },
			{ date: "2025-03-27", times: ["20:30"] },
		],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/coldplay-concert-lights-colorful-stadium.jpg",
		category: "concert",
		artist: "Coldplay",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "6-1",
				name: "Upper",
				price: 1599,
				available: 15000,
				description: "Upper tier seating",
			},
			{
				id: "6-2",
				name: "Lower",
				price: 2999,
				available: 10000,
				description: "Lower tier seating",
			},
			{
				id: "6-3",
				name: "Floor",
				price: 4999,
				available: 5000,
				description: "Floor standing area",
			},
		],
	},
	{
		id: "7",
		title: "Natanael Cano en Vivo",
		description: "El rey de los corridos tumbados en un concierto inolvidable.",
		dates: [{ date: "2025-09-14", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/regional-mexican-concert-arena-crowd.jpg",
		category: "concert",
		artist: "Natanael Cano",
		organizer: "Rancho Humilde Productions",
		ticketTypes: [
			{
				id: "7-1",
				name: "General",
				price: 899,
				available: 8000,
				description: "Arena seating",
			},
			{
				id: "7-2",
				name: "Preferred",
				price: 1499,
				available: 2000,
				description: "Lower bowl seating",
			},
			{
				id: "7-3",
				name: "VIP",
				price: 2999,
				available: 500,
				description: "VIP section with bar",
			},
		],
	},

	// Sports Events
	{
		id: "8",
		title: "Champions League Final",
		description:
			"Witness the ultimate showdown in European football. Experience the excitement live!",
		dates: [{ date: "2025-06-01", times: ["20:00"] }],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/soccer-football-stadium-match-crowd.jpg",
		category: "sports",
		artist: "UEFA Teams",
		organizer: "UEFA Mexico",
		ticketTypes: [
			{
				id: "8-1",
				name: "Upper Level",
				price: 1499,
				available: 10000,
				description: "Upper tier seating",
			},
			{
				id: "8-2",
				name: "Lower Level",
				price: 2999,
				available: 5000,
				description: "Lower tier seating",
			},
			{
				id: "8-3",
				name: "Field Side",
				price: 7999,
				available: 500,
				description: "Premium field-side seats",
			},
		],
	},
	{
		id: "9",
		title: "NBA All-Star Game",
		description:
			"The best players in basketball compete in this spectacular all-star showcase.",
		dates: [{ date: "2025-02-16", times: ["19:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/basketball-nba-arena-game-crowd.jpg",
		category: "sports",
		organizer: "NBA Mexico",
		ticketTypes: [
			{
				id: "9-1",
				name: "Upper Bowl",
				price: 2499,
				available: 8000,
				description: "Upper level seating",
			},
			{
				id: "9-2",
				name: "Lower Bowl",
				price: 4999,
				available: 4000,
				description: "Lower level seating",
			},
			{
				id: "9-3",
				name: "Courtside",
				price: 19999,
				available: 100,
				description: "Courtside seats",
			},
		],
	},
	{
		id: "10",
		title: "Lucha Libre AAA - Triplemanía",
		description:
			"El evento de lucha libre más esperado del año con las mejores estrellas.",
		dates: [{ date: "2025-08-15", times: ["19:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/lucha-libre-wrestling-arena-masks.jpg",
		category: "sports",
		organizer: "AAA Lucha Libre",
		ticketTypes: [
			{
				id: "10-1",
				name: "General",
				price: 399,
				available: 12000,
				description: "General admission",
			},
			{
				id: "10-2",
				name: "Preferente",
				price: 799,
				available: 3000,
				description: "Preferred seating",
			},
			{
				id: "10-3",
				name: "Ringside",
				price: 1999,
				available: 500,
				description: "Ringside seats",
			},
		],
	},
	{
		id: "11",
		title: "F1 Mexican Grand Prix",
		description:
			"Experience the thrill of Formula 1 racing at the legendary Autódromo Hermanos Rodríguez.",
		dates: [
			{ date: "2025-10-24", times: ["13:00"] },
			{ date: "2025-10-25", times: ["12:00"] },
			{ date: "2025-10-26", times: ["14:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Autódromo Hermanos Rodríguez",
		region: "mexico-city",
		image: "/formula-1-race-track-mexico-city-crowd.jpg",
		category: "sports",
		organizer: "Formula 1 Mexico",
		ticketTypes: [
			{
				id: "11-1",
				name: "General Admission",
				price: 2999,
				available: 50000,
				description: "3-day general access",
			},
			{
				id: "11-2",
				name: "Grandstand",
				price: 8999,
				available: 15000,
				description: "Reserved grandstand seating",
			},
			{
				id: "11-3",
				name: "Paddock Club",
				price: 49999,
				available: 500,
				description: "VIP paddock experience",
			},
		],
	},
	{
		id: "12",
		title: "Boxing: Canelo vs Champion",
		description:
			"Championship boxing match featuring Mexico's boxing legend Canelo Álvarez.",
		dates: [{ date: "2025-05-05", times: ["20:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Estadio Akron",
		region: "guadalajara",
		image: "/boxing-ring-fight-stadium-lights-crowd.jpg",
		category: "sports",
		organizer: "Golden Boy Promotions",
		ticketTypes: [
			{
				id: "12-1",
				name: "Upper Deck",
				price: 1999,
				available: 20000,
				description: "Upper stadium seating",
			},
			{
				id: "12-2",
				name: "Lower Bowl",
				price: 4999,
				available: 10000,
				description: "Lower bowl seating",
			},
			{
				id: "12-3",
				name: "Ringside",
				price: 19999,
				available: 1000,
				description: "Ringside premium seats",
			},
		],
	},

	// Theater & Arts
	{
		id: "13",
		title: "Hamilton - The Musical",
		description:
			"The revolutionary Broadway musical that tells the story of America's founding father.",
		dates: [
			{ date: "2025-05-20", times: ["19:30"] },
			{ date: "2025-05-21", times: ["15:00", "20:00"] },
			{ date: "2025-05-22", times: ["19:30"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Teatro Diana",
		region: "guadalajara",
		image: "/broadway-theater-stage-musical-performance.jpg",
		category: "theater",
		organizer: "Broadway Mexico",
		ticketTypes: [
			{
				id: "13-1",
				name: "Balcony",
				price: 599,
				available: 200,
				description: "Balcony seating",
			},
			{
				id: "13-2",
				name: "Orchestra",
				price: 1299,
				available: 150,
				description: "Main floor seating",
			},
			{
				id: "13-3",
				name: "Premium Orchestra",
				price: 1999,
				available: 50,
				description: "Front row center",
			},
		],
	},
	{
		id: "14",
		title: "Stand-Up Comedy Night",
		description:
			"An evening of laughter with top comedians from Latin America.",
		dates: [{ date: "2025-04-05", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Teatro Metropólitan",
		region: "mexico-city",
		image: "/comedy-microphone-stage-spotlight-audience.jpg",
		category: "comedy",
		artist: "Franco Escamilla",
		organizer: "Diablo Comedy",
		ticketTypes: [
			{
				id: "14-1",
				name: "General Seating",
				price: 399,
				available: 800,
				description: "Standard seating",
			},
			{
				id: "14-2",
				name: "Premium",
				price: 699,
				available: 200,
				description: "Front section seating",
			},
		],
	},
	{
		id: "15",
		title: "El Lago de los Cisnes - Ballet",
		description:
			"Una producción espectacular del clásico ballet de Tchaikovsky.",
		dates: [
			{ date: "2025-06-10", times: ["18:00"] },
			{ date: "2025-06-11", times: ["18:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Palacio de Bellas Artes",
		region: "mexico-city",
		image: "/ballet-swan-lake-stage-dancers-performance.jpg",
		category: "theater",
		organizer: "Compañía Nacional de Danza",
		ticketTypes: [
			{
				id: "15-1",
				name: "Luneta",
				price: 899,
				available: 300,
				description: "Main floor seating",
			},
			{
				id: "15-2",
				name: "Palco",
				price: 1599,
				available: 100,
				description: "Private box seating",
			},
			{
				id: "15-3",
				name: "Galería",
				price: 399,
				available: 500,
				description: "Upper gallery",
			},
		],
	},
	{
		id: "16",
		title: "The Lion King - El Rey León",
		description:
			"Disney's award-winning musical comes to life with stunning costumes and music.",
		dates: [
			{ date: "2025-07-01", times: ["18:00"] },
			{ date: "2025-07-02", times: ["15:00", "19:30"] },
			{ date: "2025-07-03", times: ["18:00"] },
		],
		location: "Monterrey, Mexico",
		venue: "Teatro de la Ciudad",
		region: "monterrey",
		image: "/lion-king-musical-stage-costumes-performance.jpg",
		category: "theater",
		organizer: "Disney Theatrical Mexico",
		ticketTypes: [
			{
				id: "16-1",
				name: "Mezzanine",
				price: 799,
				available: 400,
				description: "Mezzanine level",
			},
			{
				id: "16-2",
				name: "Orchestra",
				price: 1499,
				available: 300,
				description: "Orchestra seating",
			},
			{
				id: "16-3",
				name: "Premium",
				price: 2299,
				available: 100,
				description: "Premium front rows",
			},
		],
	},
	{
		id: "17",
		title: "Cirque du Soleil - Luzia",
		description:
			"A vibrant celebration of Mexican culture and artistry through acrobatics.",
		dates: [
			{ date: "2025-04-15", times: ["19:00"] },
			{ date: "2025-04-16", times: ["19:00"] },
			{ date: "2025-04-17", times: ["16:00", "19:30"] },
		],
		location: "Cancún, Mexico",
		venue: "Grand Top Cirque",
		region: "cancun",
		image: "/cirque-du-soleil-acrobats-performance-tent.jpg",
		category: "theater",
		organizer: "Cirque du Soleil",
		ticketTypes: [
			{
				id: "17-1",
				name: "Category C",
				price: 1299,
				available: 1000,
				description: "Side seating",
			},
			{
				id: "17-2",
				name: "Category B",
				price: 1999,
				available: 800,
				description: "Center seating",
			},
			{
				id: "17-3",
				name: "Category A",
				price: 2999,
				available: 400,
				description: "Premium front center",
			},
		],
	},

	// Conferences & Exhibitions
	{
		id: "18",
		title: "Tech Summit Mexico 2025",
		description:
			"The largest technology conference in Latin America featuring industry leaders.",
		dates: [
			{ date: "2025-09-10", times: ["09:00"] },
			{ date: "2025-09-11", times: ["09:00"] },
			{ date: "2025-09-12", times: ["09:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Centro Citibanamex",
		region: "mexico-city",
		image: "/technology-conference-speakers-stage-audience.jpg",
		category: "conference",
		organizer: "Tech Summit Organization",
		ticketTypes: [
			{
				id: "18-1",
				name: "General Pass",
				price: 2999,
				available: 5000,
				description: "3-day access to all sessions",
			},
			{
				id: "18-2",
				name: "VIP Pass",
				price: 5999,
				available: 500,
				description: "VIP lounge and networking",
			},
			{
				id: "18-3",
				name: "Platinum",
				price: 12999,
				available: 100,
				description: "Private workshops and dinners",
			},
		],
	},
	{
		id: "19",
		title: "Expo Arte Contemporáneo",
		description:
			"Showcasing the best contemporary art from Mexican and international artists.",
		dates: [
			{ date: "2025-05-01", times: ["10:00"] },
			{ date: "2025-05-02", times: ["10:00"] },
			{ date: "2025-05-03", times: ["10:00"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Expo Guadalajara",
		region: "guadalajara",
		image: "/contemporary-art-gallery-exhibition-paintings.jpg",
		category: "exhibition",
		organizer: "Arte México Foundation",
		ticketTypes: [
			{
				id: "19-1",
				name: "Single Day",
				price: 299,
				available: 2000,
				description: "One day admission",
			},
			{
				id: "19-2",
				name: "3-Day Pass",
				price: 699,
				available: 500,
				description: "All three days",
			},
			{
				id: "19-3",
				name: "Collector Pass",
				price: 1499,
				available: 100,
				description: "VIP tours and previews",
			},
		],
	},

	// Additional Events (20-100)
	{
		id: "20",
		title: "Ricardo Arjona en Concierto",
		description: "El cantautor guatemalteco presenta su tour más íntimo.",
		dates: [{ date: "2025-11-20", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/ricardo-arjona-concert-romantic-lighting.jpg",
		category: "concert",
		artist: "Ricardo Arjona",
		organizer: "Metamorfosis Producciones",
		ticketTypes: [
			{
				id: "20-1",
				name: "General",
				price: 999,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "20-2",
				name: "Preferente",
				price: 1799,
				available: 2000,
				description: "Lower level",
			},
		],
	},
	{
		id: "21",
		title: "Copa MX Final",
		description: "La gran final del torneo de copa mexicano.",
		dates: [{ date: "2025-05-15", times: ["20:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Estadio Akron",
		region: "guadalajara",
		image: "/soccer-stadium-mexico-night-lights.jpg",
		category: "sports",
		organizer: "Federación Mexicana de Fútbol",
		ticketTypes: [
			{
				id: "21-1",
				name: "General",
				price: 499,
				available: 40000,
				description: "General admission",
			},
			{
				id: "21-2",
				name: "Preferente",
				price: 899,
				available: 10000,
				description: "Preferred seating",
			},
		],
	},
	{
		id: "22",
		title: "Alejandro Sanz - Sinfónico",
		description:
			"An orchestral experience with one of Spain's greatest artists.",
		dates: [{ date: "2025-10-05", times: ["20:30"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Alejandro Sanz",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "22-1",
				name: "Luneta",
				price: 1499,
				available: 5000,
				description: "Main floor",
			},
			{
				id: "22-2",
				name: "Palco",
				price: 2999,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "23",
		title: "Festival Cervantino 2025",
		description: "El festival cultural más importante de América Latina.",
		dates: [
			{ date: "2025-10-08", times: ["18:00"] },
			{ date: "2025-10-09", times: ["18:00"] },
			{ date: "2025-10-10", times: ["18:00"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Teatro Juárez",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		organizer: "Festival Internacional Cervantino",
		ticketTypes: [
			{
				id: "23-1",
				name: "Entrada General",
				price: 399,
				available: 2000,
				description: "General access",
			},
			{
				id: "23-2",
				name: "Palco",
				price: 999,
				available: 300,
				description: "Box seating",
			},
		],
	},
	{
		id: "24",
		title: "WWE Live Mexico",
		description:
			"World Wrestling Entertainment brings the biggest superstars to Mexico.",
		dates: [{ date: "2025-07-28", times: ["19:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "sports",
		organizer: "WWE Mexico",
		ticketTypes: [
			{
				id: "24-1",
				name: "Upper Bowl",
				price: 699,
				available: 10000,
				description: "Upper seats",
			},
			{
				id: "24-2",
				name: "Floor",
				price: 1999,
				available: 3000,
				description: "Floor seating",
			},
			{
				id: "24-3",
				name: "Ringside",
				price: 4999,
				available: 500,
				description: "Ringside VIP",
			},
		],
	},
	{
		id: "25",
		title: "Yuridia en Concierto",
		description: "La voz de México en un show lleno de emoción.",
		dates: [{ date: "2025-08-22", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Yuridia",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "25-1",
				name: "General",
				price: 799,
				available: 6000,
				description: "General admission",
			},
			{
				id: "25-2",
				name: "VIP",
				price: 1599,
				available: 1000,
				description: "VIP section",
			},
		],
	},
	{
		id: "26",
		title: "Maná - Rayando el Sol Tour",
		description:
			"Rock legends Maná return with their greatest hits and new music.",
		dates: [{ date: "2025-09-25", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Estadio Jalisco",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Maná",
		organizer: "WK Entertainment",
		ticketTypes: [
			{
				id: "26-1",
				name: "General",
				price: 1299,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "26-2",
				name: "Field",
				price: 2999,
				available: 5000,
				description: "Field access",
			},
		],
	},
	{
		id: "27",
		title: "Drag Race México - Live Show",
		description: "Las reinas de Drag Race México en un espectáculo en vivo.",
		dates: [{ date: "2025-06-28", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Teatro Metropólitan",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "theater",
		organizer: "World of Wonder Mexico",
		ticketTypes: [
			{
				id: "27-1",
				name: "General",
				price: 599,
				available: 2000,
				description: "General seating",
			},
			{
				id: "27-2",
				name: "VIP",
				price: 1299,
				available: 300,
				description: "VIP with meet & greet",
			},
		],
	},
	{
		id: "28",
		title: "Molotov + Panteón Rococó",
		description: "Dos leyendas del rock mexicano en un solo escenario.",
		dates: [{ date: "2025-12-15", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Molotov, Panteón Rococó",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "28-1",
				name: "General",
				price: 899,
				available: 20000,
				description: "Standing area",
			},
			{
				id: "28-2",
				name: "VIP",
				price: 1999,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "29",
		title: "Karol G - Bichota Tour",
		description: "La Bichota llega a México con su espectacular gira mundial.",
		dates: [{ date: "2025-04-18", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Karol G",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "29-1",
				name: "General",
				price: 1499,
				available: 35000,
				description: "Stadium seating",
			},
			{
				id: "29-2",
				name: "Floor",
				price: 3999,
				available: 5000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "30",
		title: "Festival Vaivén 2025",
		description: "Festival de música alternativa e indie mexicano.",
		dates: [
			{ date: "2025-11-01", times: ["15:00"] },
			{ date: "2025-11-02", times: ["15:00"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Explanada del Estadio Jalisco",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		artist: "Little Jesus, Carla Morrison, Porter",
		organizer: "Vaivén Producciones",
		ticketTypes: [
			{
				id: "30-1",
				name: "1-Day Pass",
				price: 899,
				available: 8000,
				description: "Single day",
			},
			{
				id: "30-2",
				name: "2-Day Pass",
				price: 1599,
				available: 5000,
				description: "Both days",
			},
		],
	},
	// Events 31-100
	{
		id: "31",
		title: "Metallica - World Tour",
		description:
			"The legendary metal band performs their greatest hits and new album.",
		dates: [{ date: "2025-09-30", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Metallica",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "31-1",
				name: "General",
				price: 1999,
				available: 40000,
				description: "Stadium access",
			},
			{
				id: "31-2",
				name: "Snake Pit",
				price: 9999,
				available: 500,
				description: "Center stage circle",
			},
		],
	},
	{
		id: "32",
		title: "Feria de San Marcos 2025",
		description: "La feria más importante de México con conciertos diarios.",
		dates: [
			{ date: "2025-04-19", times: ["20:00"] },
			{ date: "2025-04-20", times: ["20:00"] },
			{ date: "2025-04-21", times: ["20:00"] },
		],
		location: "Guadalajara, Mexico",
		venue: "Palenque de la Feria",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		organizer: "Gobierno de Aguascalientes",
		ticketTypes: [
			{
				id: "32-1",
				name: "General",
				price: 599,
				available: 5000,
				description: "Standing area",
			},
			{
				id: "32-2",
				name: "Palco",
				price: 1999,
				available: 500,
				description: "Box seating",
			},
		],
	},
	{
		id: "33",
		title: "Andrea Bocelli - Concierto Sinfónico",
		description: "The Italian tenor performs with a full symphony orchestra.",
		dates: [{ date: "2025-11-10", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Andrea Bocelli",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "33-1",
				name: "Luneta",
				price: 2999,
				available: 4000,
				description: "Main floor",
			},
			{
				id: "33-2",
				name: "Palco",
				price: 5999,
				available: 800,
				description: "Box seating",
			},
		],
	},
	{
		id: "34",
		title: "Carnaval de Cancún 2025",
		description:
			"El carnaval más grande del Caribe mexicano con música y desfiles.",
		dates: [
			{ date: "2025-02-28", times: ["18:00"] },
			{ date: "2025-03-01", times: ["18:00"] },
			{ date: "2025-03-02", times: ["18:00"] },
		],
		location: "Cancún, Mexico",
		venue: "Zona Hotelera",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		organizer: "Gobierno de Quintana Roo",
		ticketTypes: [
			{
				id: "34-1",
				name: "General",
				price: 299,
				available: 20000,
				description: "Street access",
			},
			{
				id: "34-2",
				name: "Palco",
				price: 1299,
				available: 1000,
				description: "VIP viewing area",
			},
		],
	},
	{
		id: "35",
		title: "La Banda MS - Gira Nacional",
		description: "La Banda Sinaloense MS presenta sus éxitos más recientes.",
		dates: [{ date: "2025-07-12", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Banda MS",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "35-1",
				name: "General",
				price: 799,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "35-2",
				name: "VIP",
				price: 1599,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "36",
		title: "Dua Lipa - Future Nostalgia Tour",
		description: "The pop superstar brings her electrifying show to Mexico.",
		dates: [{ date: "2025-10-15", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Dua Lipa",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "36-1",
				name: "General",
				price: 1499,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "36-2",
				name: "Floor",
				price: 2999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "37",
		title: "Harry Styles - Love on Tour",
		description: "The global superstar performs hits from his latest albums.",
		dates: [
			{ date: "2025-05-28", times: ["20:30"] },
			{ date: "2025-05-29", times: ["20:30"] },
		],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Harry Styles",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "37-1",
				name: "General",
				price: 1799,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "37-2",
				name: "Floor",
				price: 3999,
				available: 8000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "38",
		title: "Los Ángeles Azules - Cumbia Sinfónica",
		description: "La cumbia mexicana se encuentra con la orquesta sinfónica.",
		dates: [{ date: "2025-12-20", times: ["20:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Los Ángeles Azules",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "38-1",
				name: "Luneta",
				price: 899,
				available: 8000,
				description: "Main floor",
			},
			{
				id: "38-2",
				name: "Palco",
				price: 1599,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "39",
		title: "Billie Eilish - Happier Than Ever Tour",
		description:
			"The Grammy-winning artist performs in an intimate arena setting.",
		dates: [{ date: "2025-11-05", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Billie Eilish",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "39-1",
				name: "Upper Bowl",
				price: 1299,
				available: 10000,
				description: "Upper seating",
			},
			{
				id: "39-2",
				name: "Floor",
				price: 2999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "40",
		title: "Festival Hellow 2025",
		description:
			"Festival de música electrónica con los mejores DJs nacionales.",
		dates: [{ date: "2025-10-31", times: ["19:00"] }],
		location: "Mexico City, Mexico",
		venue: "Autódromo Hermanos Rodríguez",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		organizer: "Hellow Festival",
		ticketTypes: [
			{
				id: "40-1",
				name: "General",
				price: 1099,
				available: 50000,
				description: "Festival access",
			},
			{
				id: "40-2",
				name: "VIP",
				price: 2999,
				available: 5000,
				description: "VIP lounge access",
			},
		],
	},
	// Events 41-100
	{
		id: "41",
		title: "Marc Anthony - Concierto",
		description: "El rey de la salsa en un concierto inolvidable.",
		dates: [{ date: "2025-08-08", times: ["21:00"] }],
		location: "Cancún, Mexico",
		venue: "Moon Palace Arena",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Marc Anthony",
		organizer: "Magnus Media",
		ticketTypes: [
			{
				id: "41-1",
				name: "General",
				price: 1499,
				available: 8000,
				description: "General admission",
			},
			{
				id: "41-2",
				name: "VIP",
				price: 3999,
				available: 1000,
				description: "VIP section",
			},
		],
	},
	{
		id: "42",
		title: "Daddy Yankee - La Última Vuelta",
		description: "The King of Reggaeton in his farewell tour.",
		dates: [{ date: "2025-12-10", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Daddy Yankee",
		organizer: "Cardenas Marketing Network",
		ticketTypes: [
			{
				id: "42-1",
				name: "General",
				price: 1599,
				available: 40000,
				description: "Stadium access",
			},
			{
				id: "42-2",
				name: "Floor",
				price: 3999,
				available: 5000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "43",
		title: "Pepe Aguilar y Familia",
		description:
			"La dinastía Aguilar en un concierto lleno de tradición mexicana.",
		dates: [{ date: "2025-09-16", times: ["20:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Pepe Aguilar",
		organizer: "Equinoccio Records",
		ticketTypes: [
			{
				id: "43-1",
				name: "General",
				price: 999,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "43-2",
				name: "VIP",
				price: 2499,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "44",
		title: "Festival Arre 2025",
		description: "Festival de música regional mexicana y banda.",
		dates: [{ date: "2025-06-14", times: ["17:00"] }],
		location: "Mexico City, Mexico",
		venue: "Autódromo Hermanos Rodríguez",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "festival",
		organizer: "Arre Entertainment",
		ticketTypes: [
			{
				id: "44-1",
				name: "General",
				price: 899,
				available: 50000,
				description: "Festival access",
			},
			{
				id: "44-2",
				name: "VIP",
				price: 2299,
				available: 5000,
				description: "VIP area",
			},
		],
	},
	{
		id: "45",
		title: "The Weeknd - After Hours Tour",
		description: "Experience the cinematic live show from the R&B superstar.",
		dates: [{ date: "2025-10-22", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "The Weeknd",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "45-1",
				name: "General",
				price: 1899,
				available: 35000,
				description: "Stadium seating",
			},
			{
				id: "45-2",
				name: "Floor",
				price: 4499,
				available: 8000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "46",
		title: "Grupo Firme en Vivo",
		description: "El grupo más popular del regional mexicano.",
		dates: [{ date: "2025-11-29", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Estadio Akron",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Grupo Firme",
		organizer: "Music VIP Entertainment",
		ticketTypes: [
			{
				id: "46-1",
				name: "General",
				price: 1299,
				available: 45000,
				description: "Stadium access",
			},
			{
				id: "46-2",
				name: "Campo",
				price: 2999,
				available: 10000,
				description: "Field area",
			},
		],
	},
	{
		id: "47",
		title: "Paul McCartney - Got Back Tour",
		description: "The legendary Beatle performs classic hits and rarities.",
		dates: [{ date: "2025-11-15", times: ["20:30"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Paul McCartney",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "47-1",
				name: "General",
				price: 2999,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "47-2",
				name: "Golden Circle",
				price: 12999,
				available: 2000,
				description: "Front stage area",
			},
		],
	},
	{
		id: "48",
		title: "Mon Laferte - Autopoiética Tour",
		description: "La cantante chileno-mexicana en su gira más personal.",
		dates: [{ date: "2025-05-25", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Mon Laferte",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "48-1",
				name: "Luneta",
				price: 899,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "48-2",
				name: "Palco",
				price: 1799,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "49",
		title: "Ed Sheeran - Mathematics Tour",
		description:
			"The singer-songwriter performs solo with his signature loop pedal.",
		dates: [
			{ date: "2025-03-20", times: ["20:30"] },
			{ date: "2025-03-21", times: ["20:30"] },
		],
		location: "Monterrey, Mexico",
		venue: "Estadio BBVA",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Ed Sheeran",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "49-1",
				name: "General",
				price: 1599,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "49-2",
				name: "Floor",
				price: 3499,
				available: 10000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "50",
		title: "Christian Nodal - Forajido Tour",
		description: "El rey del regional mexicano en su gira más esperada.",
		dates: [{ date: "2025-07-19", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Christian Nodal",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "50-1",
				name: "General",
				price: 1099,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "50-2",
				name: "VIP",
				price: 2499,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "51",
		title: "Taylor Swift - Eras Tour",
		description:
			"The record-breaking tour celebrating Taylor's entire musical journey.",
		dates: [
			{ date: "2025-08-24", times: ["19:00"] },
			{ date: "2025-08-25", times: ["19:00"] },
			{ date: "2025-08-26", times: ["19:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Estadio Azteca",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Taylor Swift",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "51-1",
				name: "General",
				price: 2499,
				available: 60000,
				description: "Stadium seating",
			},
			{
				id: "51-2",
				name: "Floor",
				price: 5999,
				available: 15000,
				description: "Floor standing",
			},
			{
				id: "51-3",
				name: "VIP Package",
				price: 19999,
				available: 1000,
				description: "VIP with merchandise",
			},
		],
	},
	{
		id: "52",
		title: "Peso Pluma - Éxodo Tour",
		description: "El fenómeno de los corridos tumbados llega a Cancún.",
		dates: [{ date: "2025-12-28", times: ["21:00"] }],
		location: "Cancún, Mexico",
		venue: "Cancún Convention Center",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Peso Pluma",
		organizer: "Prajin Entertainment",
		ticketTypes: [
			{
				id: "52-1",
				name: "General",
				price: 1299,
				available: 10000,
				description: "General admission",
			},
			{
				id: "52-2",
				name: "VIP",
				price: 2999,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "53",
		title: "Imagine Dragons - Mercury Tour",
		description: "The rock band performs their biggest hits and new material.",
		dates: [{ date: "2025-10-18", times: ["20:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Imagine Dragons",
		organizer: "Live Nation Mexico",
		ticketTypes: [
			{
				id: "53-1",
				name: "Upper Bowl",
				price: 1199,
				available: 10000,
				description: "Upper seating",
			},
			{
				id: "53-2",
				name: "Floor",
				price: 2499,
				available: 5000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "54",
		title: "Ángela Aguilar - Mexicana Enamorada",
		description: "La joven promesa del regional mexicano en concierto.",
		dates: [{ date: "2025-07-26", times: ["20:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Ángela Aguilar",
		organizer: "Equinoccio Records",
		ticketTypes: [
			{
				id: "54-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "General seating",
			},
			{
				id: "54-2",
				name: "VIP",
				price: 1599,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "55",
		title: "Shakira - Las Mujeres Ya No Lloran Tour",
		description:
			"The Colombian superstar returns to Mexico with her powerful new show.",
		dates: [{ date: "2025-03-15", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Shakira",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "55-1",
				name: "General",
				price: 1799,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "55-2",
				name: "Floor",
				price: 3499,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "56",
		title: "Café Tacvba - Gira Aniversario",
		description: "Celebrando décadas de rock alternativo mexicano.",
		dates: [{ date: "2025-11-22", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Café Tacvba",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "56-1",
				name: "Luneta",
				price: 999,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "56-2",
				name: "Palco",
				price: 1899,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "57",
		title: "Sebastián Yatra - Dharma Tour",
		description: "El cantante colombiano trae su energía a Monterrey.",
		dates: [{ date: "2025-06-07", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Sebastián Yatra",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "57-1",
				name: "General",
				price: 899,
				available: 8000,
				description: "General seating",
			},
			{
				id: "57-2",
				name: "VIP",
				price: 1799,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "58",
		title: "Rammstein - Stadium Tour",
		description:
			"The German industrial metal legends with their explosive pyrotechnic show.",
		dates: [{ date: "2025-09-12", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Rammstein",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "58-1",
				name: "General",
				price: 2299,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "58-2",
				name: "Feuerzone",
				price: 5999,
				available: 3000,
				description: "Fire zone front stage",
			},
		],
	},
	{
		id: "59",
		title: "Carla Morrison - El Renacimiento",
		description: "La cantautora mexicana en un concierto íntimo y emocional.",
		dates: [{ date: "2025-10-03", times: ["20:30"] }],
		location: "Guadalajara, Mexico",
		venue: "Teatro Diana",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Carla Morrison",
		organizer: "Cosmica Artists",
		ticketTypes: [
			{
				id: "59-1",
				name: "Platea",
				price: 799,
				available: 800,
				description: "Theater seating",
			},
			{
				id: "59-2",
				name: "Palco",
				price: 1499,
				available: 200,
				description: "Box seating",
			},
		],
	},
	{
		id: "60",
		title: "Aventura - Cerrando Ciclos Tour",
		description: "Romeo Santos y Aventura regresan juntos.",
		dates: [{ date: "2025-12-05", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Aventura",
		organizer: "Magnus Media",
		ticketTypes: [
			{
				id: "60-1",
				name: "General",
				price: 1499,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "60-2",
				name: "Floor",
				price: 2999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "61",
		title: "Wisin y Yandel - La Última Misión",
		description: "El dúo legendario del reggaeton en su gira de despedida.",
		dates: [{ date: "2025-08-30", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Wisin y Yandel",
		organizer: "WY Records",
		ticketTypes: [
			{
				id: "61-1",
				name: "General",
				price: 1299,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "61-2",
				name: "VIP",
				price: 2799,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "62",
		title: "Feid - Mor Tour",
		description:
			"El artista colombiano de reggaeton trae su show a Guadalajara.",
		dates: [{ date: "2025-09-20", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Feid",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "62-1",
				name: "General",
				price: 999,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "62-2",
				name: "Ferxxo Zone",
				price: 2299,
				available: 2000,
				description: "Special VIP area",
			},
		],
	},
	{
		id: "63",
		title: "Soda Stereo Tributo by Cerati",
		description:
			"Benito Cerati rinde homenaje a la banda legendaria de su padre.",
		dates: [{ date: "2025-11-08", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Benito Cerati",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "63-1",
				name: "Luneta",
				price: 1099,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "63-2",
				name: "Palco",
				price: 2099,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "64",
		title: "Luis Miguel - México Por Siempre",
		description: "El Sol de México en una serie de conciertos exclusivos.",
		dates: [
			{ date: "2025-12-18", times: ["21:00"] },
			{ date: "2025-12-19", times: ["21:00"] },
			{ date: "2025-12-20", times: ["21:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Luis Miguel",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "64-1",
				name: "Luneta",
				price: 2999,
				available: 5000,
				description: "Main floor",
			},
			{
				id: "64-2",
				name: "Palco",
				price: 5999,
				available: 800,
				description: "Box seating",
			},
			{
				id: "64-3",
				name: "Platea VIP",
				price: 9999,
				available: 300,
				description: "VIP orchestra",
			},
		],
	},
	{
		id: "65",
		title: "Bizarrap Session Live",
		description:
			"El productor argentino presenta sus colaboraciones más icónicas en vivo.",
		dates: [{ date: "2025-10-28", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Bizarrap",
		organizer: "Dale Play Records",
		ticketTypes: [
			{
				id: "65-1",
				name: "General",
				price: 899,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "65-2",
				name: "VIP",
				price: 1999,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "66",
		title: "Zoé - Sonidos de Karmática Resonancia",
		description: "La banda mexicana de rock alternativo en su gira especial.",
		dates: [{ date: "2025-06-21", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Zoé",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "66-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "General seating",
			},
			{
				id: "66-2",
				name: "VIP",
				price: 1599,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "67",
		title: "Enrique Iglesias - Live Concert",
		description: "The King of Latin Pop performs his greatest hits.",
		dates: [{ date: "2025-09-27", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Enrique Iglesias",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "67-1",
				name: "General",
				price: 1299,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "67-2",
				name: "Floor",
				price: 2799,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "68",
		title: "Rosalía - Motomami Tour",
		description: "La artista española revoluciona el flamenco moderno en vivo.",
		dates: [{ date: "2025-11-12", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Rosalía",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "68-1",
				name: "General",
				price: 1599,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "68-2",
				name: "Floor",
				price: 3299,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "69",
		title: "Grupo Frontera - El Comienzo Tour",
		description: "El grupo sensación del regional mexicano en Guadalajara.",
		dates: [{ date: "2025-08-16", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Grupo Frontera",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "69-1",
				name: "General",
				price: 899,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "69-2",
				name: "VIP",
				price: 1899,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "70",
		title: "Bruno Mars - 24K Magic Tour",
		description: "The funk-pop superstar brings the party to Mexico City.",
		dates: [
			{ date: "2025-04-25", times: ["21:00"] },
			{ date: "2025-04-26", times: ["21:00"] },
		],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Bruno Mars",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "70-1",
				name: "General",
				price: 1899,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "70-2",
				name: "Floor",
				price: 3999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "71",
		title: "Rauw Alejandro - Saturno World Tour",
		description: "El todo terreno del reggaeton llega a Cancún.",
		dates: [{ date: "2025-07-05", times: ["21:00"] }],
		location: "Cancún, Mexico",
		venue: "Cancún Convention Center",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Rauw Alejandro",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "71-1",
				name: "General",
				price: 1199,
				available: 10000,
				description: "General admission",
			},
			{
				id: "71-2",
				name: "VIP",
				price: 2499,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "72",
		title: "Enanitos Verdes - Gira 40 Años",
		description: "Celebrando cuatro décadas de rock latino.",
		dates: [{ date: "2025-05-17", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Enanitos Verdes",
		organizer: "Promotora del Rock",
		ticketTypes: [
			{
				id: "72-1",
				name: "General",
				price: 699,
				available: 8000,
				description: "General seating",
			},
			{
				id: "72-2",
				name: "VIP",
				price: 1299,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "73",
		title: "Caifanes - El Diablito Tour",
		description: "La banda icónica del rock mexicano en concierto.",
		dates: [{ date: "2025-12-12", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Caifanes",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "73-1",
				name: "General",
				price: 899,
				available: 8000,
				description: "General seating",
			},
			{
				id: "73-2",
				name: "VIP",
				price: 1799,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "74",
		title: "Elton John - Farewell Yellow Brick Road",
		description: "The legendary performer in his final tour.",
		dates: [{ date: "2025-03-08", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Elton John",
		organizer: "OCESA Presents",
		ticketTypes: [
			{
				id: "74-1",
				name: "General",
				price: 2499,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "74-2",
				name: "Golden Circle",
				price: 9999,
				available: 2000,
				description: "Front stage area",
			},
		],
	},
	{
		id: "75",
		title: "Maluma - Don Juan Tour",
		description: "Pretty boy, dirty boy en su gira mundial.",
		dates: [{ date: "2025-06-15", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Maluma",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "75-1",
				name: "General",
				price: 1399,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "75-2",
				name: "Floor",
				price: 2899,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "76",
		title: "Intocable - 30 Años de Historia",
		description: "La banda tejana celebra tres décadas de éxitos.",
		dates: [{ date: "2025-09-05", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Intocable",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "76-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "General seating",
			},
			{
				id: "76-2",
				name: "VIP",
				price: 1599,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "77",
		title: "J Balvin - Rayo Tour",
		description: "El príncipe del reggaeton en un show lleno de color.",
		dates: [{ date: "2025-10-10", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Palacio de los Deportes",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "J Balvin",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "77-1",
				name: "General",
				price: 1499,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "77-2",
				name: "Floor",
				price: 2999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "78",
		title: "Panteón Rococó - Ejército de Paz",
		description: "La banda de ska mexicano en su gira más energética.",
		dates: [{ date: "2025-08-29", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Panteón Rococó",
		organizer: "Movic Records",
		ticketTypes: [
			{
				id: "78-1",
				name: "General",
				price: 599,
				available: 8000,
				description: "General seating",
			},
			{
				id: "78-2",
				name: "VIP",
				price: 1199,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "79",
		title: "Becky G - Esquinas Tour",
		description: "La artista méxico-americana celebra sus raíces.",
		dates: [{ date: "2025-07-31", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Becky G",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "79-1",
				name: "General",
				price: 999,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "79-2",
				name: "Floor",
				price: 2299,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "80",
		title: "Los Tigres del Norte - Historia Musical",
		description: "Los legendarios de la música norteña en concierto.",
		dates: [{ date: "2025-09-13", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Los Tigres del Norte",
		organizer: "Fonovisa Records",
		ticketTypes: [
			{
				id: "80-1",
				name: "General",
				price: 899,
				available: 8000,
				description: "General seating",
			},
			{
				id: "80-2",
				name: "VIP",
				price: 1799,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "81",
		title: "Ozuna - Ozutochi Tour",
		description: "El negrito de ojos claros en su gira mundial.",
		dates: [{ date: "2025-11-28", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Ozuna",
		organizer: "Aura Music",
		ticketTypes: [
			{
				id: "81-1",
				name: "General",
				price: 1199,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "81-2",
				name: "VIP",
				price: 2499,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "82",
		title: "Maná + Enanitos Verdes - Rock Latino",
		description: "Dos leyendas del rock latino en una noche única.",
		dates: [{ date: "2025-10-25", times: ["20:00"] }],
		location: "Mexico City, Mexico",
		venue: "Foro Sol",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Maná, Enanitos Verdes",
		organizer: "WK Entertainment",
		ticketTypes: [
			{
				id: "82-1",
				name: "General",
				price: 1499,
				available: 40000,
				description: "Stadium seating",
			},
			{
				id: "82-2",
				name: "Field",
				price: 3499,
				available: 5000,
				description: "Field access",
			},
		],
	},
	{
		id: "83",
		title: "Nicki Nicole - Alma Tour",
		description: "La artista argentina de trap y R&B llega a Cancún.",
		dates: [{ date: "2025-12-30", times: ["21:00"] }],
		location: "Cancún, Mexico",
		venue: "Moon Palace Arena",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Nicki Nicole",
		organizer: "Dale Play Records",
		ticketTypes: [
			{
				id: "83-1",
				name: "General",
				price: 899,
				available: 8000,
				description: "General admission",
			},
			{
				id: "83-2",
				name: "VIP",
				price: 1799,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "84",
		title: "Reik - Panorama Tour",
		description: "El trío mexicano de pop romántico en concierto.",
		dates: [{ date: "2025-08-23", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Reik",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "84-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "General seating",
			},
			{
				id: "84-2",
				name: "VIP",
				price: 1599,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "85",
		title: "Little Jesus - Disco de Oro Tour",
		description: "La banda indie mexicana presenta su nuevo material.",
		dates: [{ date: "2025-11-14", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Teatro Diana",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Little Jesus",
		organizer: "Cosmica Artists",
		ticketTypes: [
			{
				id: "85-1",
				name: "General",
				price: 599,
				available: 1500,
				description: "Theater seating",
			},
			{
				id: "85-2",
				name: "VIP",
				price: 999,
				available: 300,
				description: "VIP section",
			},
		],
	},
	{
		id: "86",
		title: "Los Bukis - Una Historia Cantada",
		description: "Marco Antonio Solís y Los Bukis en su histórica reunión.",
		dates: [{ date: "2025-04-12", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Estadio Azteca",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Los Bukis",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "86-1",
				name: "General",
				price: 1299,
				available: 60000,
				description: "Stadium seating",
			},
			{
				id: "86-2",
				name: "Field",
				price: 2999,
				available: 10000,
				description: "Field area",
			},
		],
	},
	{
		id: "87",
		title: "Danna Paola - XT4S1S Tour",
		description: "La estrella mexicana en su gira más ambiciosa.",
		dates: [{ date: "2025-06-27", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Danna Paola",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "87-1",
				name: "Luneta",
				price: 999,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "87-2",
				name: "Palco",
				price: 1899,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "88",
		title: "Residente - Las Letras Ya No Importan",
		description: "El ex-Calle 13 presenta su show más personal y político.",
		dates: [{ date: "2025-09-18", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Residente",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "88-1",
				name: "General",
				price: 899,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "88-2",
				name: "VIP",
				price: 1899,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "89",
		title: "Kany García - García Tour",
		description: "La cantautora puertorriqueña en un concierto íntimo.",
		dates: [{ date: "2025-10-17", times: ["20:30"] }],
		location: "Guadalajara, Mexico",
		venue: "Teatro Diana",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Kany García",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "89-1",
				name: "Platea",
				price: 799,
				available: 1500,
				description: "Theater seating",
			},
			{
				id: "89-2",
				name: "Palco",
				price: 1499,
				available: 300,
				description: "Box seating",
			},
		],
	},
	{
		id: "90",
		title: "Tini - Cupido Tour",
		description: "La artista argentina trae su show lleno de energía.",
		dates: [{ date: "2025-07-11", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Arena Ciudad de México",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Tini",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "90-1",
				name: "General",
				price: 899,
				available: 15000,
				description: "Arena seating",
			},
			{
				id: "90-2",
				name: "Floor",
				price: 1999,
				available: 3000,
				description: "Floor standing",
			},
		],
	},
	{
		id: "91",
		title: "Los Fabulosos Cadillacs - La Marcha del Golazo",
		description: "La legendaria banda de ska argentina regresa a México.",
		dates: [{ date: "2025-05-30", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Auditorio Citibanamex",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Los Fabulosos Cadillacs",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "91-1",
				name: "General",
				price: 799,
				available: 8000,
				description: "General seating",
			},
			{
				id: "91-2",
				name: "VIP",
				price: 1599,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "92",
		title: "María Becerra - Animal Tour",
		description: "La nena de Argentina en su gira más esperada.",
		dates: [{ date: "2025-12-06", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Arena VFG",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "María Becerra",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "92-1",
				name: "General",
				price: 999,
				available: 10000,
				description: "Arena seating",
			},
			{
				id: "92-2",
				name: "VIP",
				price: 2099,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "93",
		title: "Calibre 50 - Contigo Tour",
		description: "La banda sinaloense en su gira por todo México.",
		dates: [{ date: "2025-08-09", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Calibre 50",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "93-1",
				name: "General",
				price: 899,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "93-2",
				name: "VIP",
				price: 1799,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "94",
		title: "Alejandra Guzmán - Perrísimas Tour",
		description: "La reina del rock mexicano en todo su esplendor.",
		dates: [{ date: "2025-11-21", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Alejandra Guzmán",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "94-1",
				name: "Luneta",
				price: 999,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "94-2",
				name: "Palco",
				price: 1999,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "95",
		title: "Camilo - De Adentro Pa Afuera Tour",
		description: "El cantautor colombiano en un show íntimo y emocional.",
		dates: [{ date: "2025-06-06", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Camilo",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "95-1",
				name: "General",
				price: 999,
				available: 8000,
				description: "General seating",
			},
			{
				id: "95-2",
				name: "VIP",
				price: 1999,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "96",
		title: "Jesse & Joy - Corre! Tour",
		description: "El dúo mexicano presenta sus éxitos y nuevo material.",
		dates: [{ date: "2025-09-26", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Jesse & Joy",
		organizer: "Warner Music Mexico",
		ticketTypes: [
			{
				id: "96-1",
				name: "Luneta",
				price: 899,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "96-2",
				name: "Palco",
				price: 1799,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "97",
		title: "Gerardo Ortiz - Cuidado Tour",
		description: "El rey del corrido en su gira por Monterrey.",
		dates: [{ date: "2025-10-11", times: ["21:00"] }],
		location: "Monterrey, Mexico",
		venue: "Arena Monterrey",
		region: "monterrey",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Gerardo Ortiz",
		organizer: "Del Records",
		ticketTypes: [
			{
				id: "97-1",
				name: "General",
				price: 899,
				available: 12000,
				description: "Arena seating",
			},
			{
				id: "97-2",
				name: "VIP",
				price: 1799,
				available: 2000,
				description: "VIP section",
			},
		],
	},
	{
		id: "98",
		title: "Juanes - Vida Cotidiana Tour",
		description: "El colombiano ganador de múltiples Grammys en concierto.",
		dates: [{ date: "2025-07-18", times: ["21:00"] }],
		location: "Guadalajara, Mexico",
		venue: "Auditorio Telmex",
		region: "guadalajara",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Juanes",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "98-1",
				name: "General",
				price: 999,
				available: 8000,
				description: "General seating",
			},
			{
				id: "98-2",
				name: "VIP",
				price: 1999,
				available: 1500,
				description: "VIP section",
			},
		],
	},
	{
		id: "99",
		title: "Sin Bandera - Volviendo Tour",
		description: "El dúo mexicano-argentino regresa en su gira de reencuentro.",
		dates: [{ date: "2025-12-13", times: ["21:00"] }],
		location: "Mexico City, Mexico",
		venue: "Auditorio Nacional",
		region: "mexico-city",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Sin Bandera",
		organizer: "Sony Music Mexico",
		ticketTypes: [
			{
				id: "99-1",
				name: "Luneta",
				price: 1099,
				available: 6000,
				description: "Main floor",
			},
			{
				id: "99-2",
				name: "Palco",
				price: 2099,
				available: 1000,
				description: "Box seating",
			},
		],
	},
	{
		id: "100",
		title: "Gloria Trevi - Isla Divina Tour",
		description: "La diva mexicana cierra el año con un show espectacular.",
		dates: [{ date: "2025-12-31", times: ["22:00"] }],
		location: "Cancún, Mexico",
		venue: "Moon Palace Arena",
		region: "cancun",
		image: "/placeholder.svg?height=400&width=600",
		category: "concert",
		artist: "Gloria Trevi",
		organizer: "Universal Music Mexico",
		ticketTypes: [
			{
				id: "100-1",
				name: "General",
				price: 1499,
				available: 8000,
				description: "General admission",
			},
			{
				id: "100-2",
				name: "VIP",
				price: 2999,
				available: 1500,
				description: "VIP New Year's package",
			},
		],
	},
];

export const mockUsers: User[] = [];
export const mockOrders: Order[] = [];
